/**
 * Data loader utility - re-exports from generated module
 * 
 * The actual implementation is generated at build time by the Vite plugin
 * based on VITE_SCHEDULES_FILE environment variable.
 * 
 * Usage:
 * - Set VITE_SCHEDULES_FILE in .env (e.g., "schedule-karen.json" or "schedule-john.json")
 * - Schedule files should follow the format: schedule-XXX.json
 * - Paths are relative to src/data directory
 * - REQUIRED: VITE_SCHEDULES_FILE must be set or the build will fail
 * 
 * Note: 
 * - Environment variables are resolved at BUILD TIME, so you must rebuild after changing them
 * - Only the specified schedule file will be bundled (not all JSON files)
 * - Files must be in src/data/ directory
 * - Build will fail if VITE_SCHEDULES_FILE is not set
 */

// Re-export from the generated module
// This file is generated by the Vite plugin at build time
export { loadSchedules } from "./data-loader-generated";
