import path from "path";
import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import { defineConfig, Plugin } from "vite";
import fs from "fs";

/**
 * Vite plugin that generates a data loader module based on environment variables
 * This ensures only the specified schedule JSON file is bundled at build time
 * Itineraries are loaded statically and don't need to be configured
 */
function dataLoaderPlugin(): Plugin {
  return {
    name: "data-loader-plugin",
    buildStart() {
      // Read env var for schedule file (format: schedule-XXX.json)
      // Fail if not specified
      const schedulesFile = process.env.VITE_SCHEDULES_FILE;
      
      if (!schedulesFile) {
        throw new Error(
          "VITE_SCHEDULES_FILE environment variable is required. " +
          "Please set it in your .env file or as an environment variable. " +
          "Example: VITE_SCHEDULES_FILE=schedule-XXX.json"
        );
      }

      // Normalize path (remove leading data/ or /)
      const normalizePath = (filePath: string) => {
        return filePath.replace(/^\/?data\//, "").replace(/^\//, "");
      };

      const schedulesPath = normalizePath(schedulesFile);

      // Generate the data loader module
      // Itineraries are always loaded from the same static file
      const loaderCode = `/**
 * Auto-generated data loader module
 * This file is generated at build time based on VITE_SCHEDULES_FILE
 * DO NOT EDIT THIS FILE MANUALLY
 */

import schedulesData from "@/data/${schedulesPath}";

export function loadSchedules() {
  return schedulesData;
}
`;

      // Write the generated file
      const outputPath = path.resolve(__dirname, "src/lib/data-loader-generated.ts");
      fs.writeFileSync(outputPath, loaderCode, "utf-8");
    },
  };
}

// https://vite.dev/config/
export default defineConfig({
  plugins: [react(), tailwindcss(), dataLoaderPlugin()],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
});
