import type { Cruise } from "@/types/cruise";

export const cruises: Cruise[] = [
  {
    id: "cruise-1",
    name: "Caribbean Paradise",
    shipName: "Royal Voyager",
    departureDate: "2025-06-10",
    returnDate: "2025-06-17",
    duration: 7,
    departurePort: "Miami, FL",
    returnPort: "Miami, FL",
    region: "Caribbean",
    price: 899,
    stops: [
      { day: 1, port: "Miami, FL", departureTime: "4:00 PM" },
      { day: 2, port: "At Sea" },
      {
        day: 3,
        port: "Cozumel, Mexico",
        arrivalTime: "8:00 AM",
        departureTime: "5:00 PM",
      },
      {
        day: 4,
        port: "Grand Cayman",
        arrivalTime: "8:00 AM",
        departureTime: "4:00 PM",
      },
      {
        day: 5,
        port: "Falmouth, Jamaica",
        arrivalTime: "10:00 AM",
        departureTime: "6:00 PM",
      },
      { day: 6, port: "At Sea" },
      { day: 7, port: "Miami, FL", arrivalTime: "7:00 AM" },
    ],
    bookingUrl: "https://example.com/cruise-1",
  },
  {
    id: "cruise-2",
    name: "Eastern Caribbean Adventure",
    shipName: "Royal Voyager",
    departureDate: "2025-06-17",
    returnDate: "2025-06-24",
    duration: 7,
    departurePort: "Miami, FL",
    returnPort: "Miami, FL",
    region: "Caribbean",
    price: 949,
    stops: [
      { day: 1, port: "Miami, FL", departureTime: "4:00 PM" },
      { day: 2, port: "At Sea" },
      {
        day: 3,
        port: "San Juan, Puerto Rico",
        arrivalTime: "8:00 AM",
        departureTime: "5:00 PM",
      },
      {
        day: 4,
        port: "St. Thomas, USVI",
        arrivalTime: "8:00 AM",
        departureTime: "4:00 PM",
      },
      {
        day: 5,
        port: "St. Maarten",
        arrivalTime: "10:00 AM",
        departureTime: "6:00 PM",
      },
      { day: 6, port: "At Sea" },
      { day: 7, port: "Miami, FL", arrivalTime: "7:00 AM" },
    ],
    bookingUrl: "https://example.com/cruise-2",
  },
  {
    id: "cruise-3",
    name: "Mediterranean Splendor",
    shipName: "Oceanic Explorer",
    departureDate: "2025-07-15",
    returnDate: "2025-07-26",
    duration: 11,
    departurePort: "Barcelona, Spain",
    returnPort: "Rome, Italy",
    region: "Mediterranean",
    price: 1299,
    stops: [
      { day: 1, port: "Barcelona, Spain", departureTime: "5:00 PM" },
      { day: 2, port: "At Sea" },
      {
        day: 3,
        port: "Provence (Marseille), France",
        arrivalTime: "8:00 AM",
        departureTime: "6:00 PM",
      },
      {
        day: 4,
        port: "Florence/Pisa (Livorno), Italy",
        arrivalTime: "7:00 AM",
        departureTime: "7:00 PM",
      },
      {
        day: 5,
        port: "Rome (Civitavecchia), Italy",
        arrivalTime: "7:00 AM",
        departureTime: "8:00 PM",
      },
      {
        day: 6,
        port: "Naples, Italy",
        arrivalTime: "7:00 AM",
        departureTime: "6:30 PM",
      },
      { day: 7, port: "At Sea" },
      {
        day: 8,
        port: "Santorini, Greece",
        arrivalTime: "7:00 AM",
        departureTime: "7:00 PM",
      },
      {
        day: 9,
        port: "Athens (Piraeus), Greece",
        arrivalTime: "6:00 AM",
        departureTime: "6:00 PM",
      },
      { day: 10, port: "At Sea" },
      { day: 11, port: "Rome (Civitavecchia), Italy", arrivalTime: "5:00 AM" },
    ],
    bookingUrl: "https://example.com/cruise-3",
  },
  {
    id: "cruise-4",
    name: "Alaskan Wilderness",
    shipName: "Northern Star",
    departureDate: "2025-08-05",
    returnDate: "2025-08-12",
    duration: 7,
    departurePort: "Seattle, WA",
    returnPort: "Seattle, WA",
    region: "Alaska",
    price: 1099,
    stops: [
      { day: 1, port: "Seattle, WA", departureTime: "4:00 PM" },
      { day: 2, port: "At Sea" },
      {
        day: 3,
        port: "Juneau, Alaska",
        arrivalTime: "12:00 PM",
        departureTime: "9:00 PM",
      },
      {
        day: 4,
        port: "Skagway, Alaska",
        arrivalTime: "7:00 AM",
        departureTime: "8:30 PM",
      },
      { day: 5, port: "Glacier Bay (Scenic Cruising)" },
      {
        day: 6,
        port: "Ketchikan, Alaska",
        arrivalTime: "10:00 AM",
        departureTime: "6:00 PM",
      },
      {
        day: 7,
        port: "Victoria, BC, Canada",
        arrivalTime: "6:00 PM",
        departureTime: "11:59 PM",
      },
      { day: 8, port: "Seattle, WA", arrivalTime: "7:00 AM" },
    ],
    bookingUrl: "https://example.com/cruise-4",
  },
  {
    id: "cruise-5",
    name: "Greek Isles Explorer",
    shipName: "Oceanic Explorer",
    departureDate: "2025-07-26",
    returnDate: "2025-08-02",
    duration: 7,
    departurePort: "Rome, Italy",
    returnPort: "Athens, Greece",
    region: "Mediterranean",
    price: 1199,
    stops: [
      { day: 1, port: "Rome (Civitavecchia), Italy", departureTime: "5:00 PM" },
      { day: 2, port: "At Sea" },
      {
        day: 3,
        port: "Santorini, Greece",
        arrivalTime: "7:00 AM",
        departureTime: "7:00 PM",
      },
      {
        day: 4,
        port: "Mykonos, Greece",
        arrivalTime: "7:00 AM",
        departureTime: "7:00 PM",
      },
      {
        day: 5,
        port: "Rhodes, Greece",
        arrivalTime: "8:00 AM",
        departureTime: "6:00 PM",
      },
      {
        day: 6,
        port: "Crete (Heraklion), Greece",
        arrivalTime: "7:00 AM",
        departureTime: "5:00 PM",
      },
      { day: 7, port: "Athens (Piraeus), Greece", arrivalTime: "6:00 AM" },
    ],
    bookingUrl: "https://example.com/cruise-5",
  },
];
